# Generated by Django 2.2.7 on 2019-11-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='beer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default='city', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='cococola',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='coffee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(default='country', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='english_speaking',
            field=models.CharField(default='language', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='female_ratio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='free_wifi',
            field=models.CharField(default='wifi', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='internet',
            field=models.CharField(default='internet', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='male_ratio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='nomad_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, default='img', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, default='img', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, default='img', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, default='img', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(blank=True, default='img', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(default='img', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(default='state', max_length=100),
        ),
    ]
